services:
  nut-upsd:
    image: instantlinux/nut-upsd:latest
    container_name: nut-upsd
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-America/Denver}
      - API_PASSWORD=${API_PASSWORD:-YourPasswordForAPIaccess}
      - DRIVER=usbhid-ups
    labels:
      # Main
      traefik.enable: false
      runtipi.managed: true
